---
pool: 
  vmImage: 'ubuntu-22.04'
trigger: 
  - main
stages:
  - stage: 'build'
    jobs:
    - job: 'build_project'
      steps: 
      - task: 'Maven@3'
        inputs:
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'clean package'
          publishJUnitResults: true
          jdkVersionOption: '1.11' 
        displayName: 'Building project'  
  - stage: 'sonar'
    jobs:
    - job: 'sonarqube'
      steps:
        - task: "SonarQubeAnalyze@4"  
