---
  pipeline:
    pool:
      vmImage: 'ubuntu-22.04'
    trigger:
      - main
    stages:
      - stage: "Clone"
        jobs:
          - job: Clone job
            steps: 
              - script: 'git clone https://github.com/IsmailAhmed98/spring-petclinic.git'
                displayName: Cloning Petclinic project
      - stage: "Build"
        jobs:
          - job: build job
            steps:
              - task: Maven@4
                inputs: 
                  goals: package
                  testResultsFiles: '**/surefire-reports/TEST-*.xml'
                  jdkVersionOption: '1.11'
                displayName: Building project
