apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-project
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: spc-project
  template:
    metadata: 
      labels: 
        app: spc-project
    spec:
      containers:
        - image: ismailahmed09/spring-petclinic:1.0
          name: spc-project
          ports: 
            - containerPort: 8081
