apiVersion: v1
kind: Service
metadata:
  name: spc-project
spec:
  selector:
    app: spc-project
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30081
      protocol: TCP
  type: NodePort
